dist: bionic
language: go
sudo: false

matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
      env: WITH_FUZZ=true
      services:
        - docker
    - go: tip

before_install:
  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/miekg
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/miekg/ || true

script:
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...
  - ./fuzzit.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
